### ISSUE TITLE
Install mechanicsoup failed

### ISSUE THREAD

**Issue by nishit130** [abdallahelsokary/TwitterSniper#3]
![screenshot_20180311-093744](https://user-images.githubusercontent.com/35602510/37249555-e3cd617e-250f-11e8-91aa-bd8fe48b2be6.jpeg)
Whrn i trying to install it on my mobile emulator i m getting this msg..  of failed "arm-linux-androideabi-clang"

**Comment by ghost** [comment]
I have the same problem. And TwitterSniper cannot run.

**Comment by willuhmjs** [comment]
mechanicalsoup is only valid on certain devices. You need to try running it on a computer. The emulator that I found that works is repl.it, if you don't wanna try it on a computer.

`pip install mechanicalsoup`

Good Luck
